export const localization = {
    signUp: {
        start: {
          title: 'أنشئ حسابك',
          subtitle: 'للمتابعة إلى {{applicationName}}',
          actionText: 'هل لديك حساب؟',
          actionLink: 'تسجيل الدخول',
        },
    },
    socialButtonsBlockButton: 'تابع مع {{provider|titleize}}',
    dividerText:'أو',
  formFieldLabel__emailAddress: 'عنوان البريد الإلكتروني',
  formFieldLabel__emailAddresses: 'عناوين البريد الإلكتروني',
  formFieldLabel__phoneNumber: 'رقم الهاتف',
  formFieldLabel__username: 'اسم المستخدم',
  formFieldLabel__emailAddress_phoneNumber: 'عنوان البريد الإلكتروني أو رقم الهاتف',
  formFieldLabel__emailAddress_username: 'عنوان البريد الإلكتروني أو اسم المستخدم',
  formFieldLabel__phoneNumber_username: 'رقم الهاتف أو اسم المستخدم',
  formFieldLabel__emailAddress_phoneNumber_username: 'عنوان البريد الإلكتروني أو رقم الهاتف أو اسم المستخدم',
  formFieldLabel__password: 'كلمة المرور',
  formFieldLabel__currentPassword: 'كلمة السر الحالية',
  formFieldLabel__newPassword: 'كلمة المرور الجديدة',
  formFieldLabel__confirmPassword: 'تأكيد كلمة المرور',
  formFieldLabel__signOutOfOtherSessions: 'تسجيل الخروج من جميع الأجهزة الأخرى',
  formFieldLabel__automaticInvitations: 'تفعيل الدعوات التلقائية لهذا المجال',
  formFieldLabel__firstName: 'الاسم الأول',
  formFieldLabel__lastName: 'اسم العائلة',
  formFieldLabel__backupCode: 'كود النسخ الاحتياطي',
  formFieldLabel__organizationName: 'اسم المنظمة',
  formFieldLabel__organizationEmailDomain: 'مجال البريد الإلكتروني',
  formFieldLabel__confirmDeletion: 'تأكيد',
  formFieldLabel__role: 'الدور',
  formFieldError__notMatchingPasswords: `كلمات المرور غير متطابقة.`,
  formFieldError__matchingPasswords: 'كلمات السر متطابقة.',
  formFieldAction__forgotPassword: 'هل نسيت كلمة السر؟',
  formFieldHintText__optional: 'خياري',
  formButtonPrimary: 'أكمل',
  signInEnterPasswordTitle: 'أدخل كلمة مرورك',
  backButton: 'عودة',
  footerActionLink__useAnotherMethod: 'استخدم طريقة أخرى',
  badge__primary: 'أساسي',
  badge__thisDevice: 'هذا الجهاز',
  badge__userDevice: 'جهاز المستخدم',
  badge__otherImpersonatorDevice: 'جهاز منتحل آخر',
  badge__default: 'إفتراضي',
  badge__unverified: 'لم يتم التحقق منه',
  badge__requiresAction: 'يتطلب اتخاذ إجراءات',
  badge__you: 'أنت',
  footerPageLink__help: 'مساعدة',
  footerPageLink__privacy: 'خصوصية',
  footerPageLink__terms: 'شروط',
  paginationButton__previous: 'السابق',
  paginationButton__next: 'التالي',
  paginationRowText__displaying: 'العرض',
  paginationRowText__of: 'of',
  membershipRole__admin: 'Admin',
  membershipRole__basicMember: 'Member',
  membershipRole__guestMember: 'Guest',

  signIn: {
    start: {
      title: 'تسجيل الدخول',
      subtitle: 'للاستمرار في {{applicationName}}',
      actionText: 'لا حساب؟',
      actionLink: 'قم بالتسجيل',
      actionLink__use_email: 'استخدم البريد الإلكتروني',
      actionLink__use_phone: 'استخدام الهاتف',
      actionLink__use_username: 'استخدم اسم المستخدم',
      actionLink__use_email_username: 'استخدم البريد الإلكتروني أو اسم المستخدم',
    },
},

userButton: {
    action__manageAccount: 'إدارة الحساب',
    action__signOut: 'تسجيل الخروج',
    action__signOutAll: 'تسجيل الخروج من جميع الحسابات',
    action__addAccount: 'إضافة حساب',
  },
  userProfile: {
    mobileButton__menu: 'القائمة',
    formButtonPrimary__continue: 'استمر',
    formButtonPrimary__finish: 'إنهاء',
    formButtonReset: 'إلغاء',
    start: {
      headerTitle__account: 'الحساب',
      headerTitle__security: 'الأمان',
      headerSubtitle__account: 'إدارة معلومات حسابك',
      headerSubtitle__security: 'إدارة تفضيلات الأمان لديك',
      profileSection: {
        title: 'الملف الشخصي',
      },
      usernameSection: {
        title: 'اسم المستخدم',
        primaryButton__changeUsername: 'تغيير اسم المستخدم',
        primaryButton__setUsername: 'تعيين اسم المستخدم',
      },
      emailAddressesSection: {
        title: 'عناوين البريد الإلكتروني',
        primaryButton: 'إضافة عنوان بريد إلكتروني',
        detailsTitle__primary: 'عنوان البريد الإلكتروني الأساسي',
        detailsSubtitle__primary: 'هذا البريد الإلكتروني هو البريد الإلكتروني الأساسي',
        detailsAction__primary: 'إكمال التحقق',
        detailsTitle__nonPrimary: 'تعيين كعنوان بريد إلكتروني أساسي',
        detailsSubtitle__nonPrimary:
          'حدد هذا البريد الإلكتروني كبريد إلكتروني أساسي لتلقي الاتصالات بخصوص حسابك.',
        detailsAction__nonPrimary: 'تعيين كأساسي',
        detailsTitle__unverified: 'عنوان البريد الإلكتروني غير متحقق منه',
        detailsSubtitle__unverified: 'لم يتم التحقق من هذا البريد الإلكتروني وقد يكون محدودًا في الوظائف',
        detailsAction__unverified: 'إكمال التحقق',
        destructiveActionTitle: 'إزالة',
        destructiveActionSubtitle: 'حذف هذا البريد الإلكتروني وإزالته من حسابك',
        destructiveAction: 'إزالة عنوان البريد الإلكتروني',
      },
      phoneNumbersSection: {
        title: 'أرقام الهاتف',
        primaryButton: 'إضافة رقم هاتف',
        detailsTitle__primary: 'رقم الهاتف الأساسي',
        detailsSubtitle__primary: 'هذا الرقم هو رقم الهاتف الأساسي',
        detailsAction__primary: 'إكمال التحقق',
        detailsTitle__nonPrimary: 'تعيين كرقم هاتف أساسي',
        detailsSubtitle__nonPrimary:
          'حدد هذا الرقم كرقم هاتف أساسي لتلقي الاتصالات بخصوص حسابك.',
        detailsAction__nonPrimary: 'تعيين كأساسي',
        detailsTitle__unverified: 'رقم الهاتف غير متحقق منه',
        detailsSubtitle__unverified: 'لم يتم التحقق من هذا الرقم وقد يكون محدودًا في الوظائف',
        detailsAction__unverified: 'إكمال التحقق',
        destructiveActionTitle: 'إزالة',
        destructiveActionSubtitle: 'حذف هذا الرقم وإزالته من حسابك',
        destructiveAction: 'إزالة رقم الهاتف',
      },
      connectedAccountsSection: {
        title: 'الحسابات المتصلة',
        primaryButton: 'ربط الحساب',
        title__conectionFailed: 'إعادة المحاولة فشلت في الاتصال',
        title__connectionFailed: 'إعادة المحاولة فشلت في الاتصال',
        title__reauthorize: 'إعادة التفويض مطلوبة',
        subtitle__reauthorize:
          'تم تحديث النطاقات المطلوبة، وقد تواجه وظائف محدودة. يرجى إعادة تفويض هذا التطبيق لتجنب أي مشكلات',
        actionLabel__conectionFailed: 'حاول مرة أخرى',
        actionLabel__connectionFailed: 'حاول مرة أخرى',
        actionLabel__reauthorize: 'التفويض الآن',
        destructiveActionTitle: 'إزالة',
        destructiveActionSubtitle: 'إزالة هذا الحساب المتصل من حسابك',
        destructiveActionAccordionSubtitle: 'إزالة الحساب المتصل',
      },
      enterpriseAccountsSection: {
        title: 'حسابات الشركات',
      },
      passwordSection: {
        title: 'كلمة المرور',
        primaryButton__changePassword: 'تغيير كلمة المرور',
        primaryButton__setPassword: 'تعيين كلمة المرور',
      },
      mfaSection: {
        title: 'التحقق بخطوتين',
        primaryButton: 'إضافة التحقق بخطوتين',
        phoneCode: {
          destructiveActionTitle: 'إزالة',
          destructiveActionSubtitle: 'إزالة هذا الرقم من طرق التحقق بخطوتين',
          destructiveActionLabel: 'إزالة رقم الهاتف',
          title__default: 'عامل افتراضي',
          title__setDefault: 'تعيين كعامل افتراضي',
          subtitle__default: 'سيتم استخدام هذا العامل كطريقة تحقق افتراضية عند تسجيل الدخول.',
          subtitle__setDefault:
            'قم بتعيين هذا العامل كعامل افتراضي لاستخدامه كطريقة تحقق افتراضية عند تسجيل الدخول.',
          actionLabel__setDefault: 'تعيين كافتراضي',
        },
        backupCodes: {
          headerTitle: 'أكواد النسخ الاحتياطي',
          title__regenerate: 'إعادة توليد أكواد النسخ الاحتياطي',
          subtitle__regenerate:
            'الحصول على مجموعة جديدة من أكواد النسخ الاحتياطي الآمنة. سيتم حذف الأكواد الاحتياطية السابقة ولا يمكن استخدامها.',
          actionLabel__regenerate: 'إعادة توليد الأكواد',
        },
        totp: {
          headerTitle: 'تطبيق المصادقة',
          title: 'عامل افتراضي',
          subtitle: 'سيتم استخدام هذا العامل كطريقة تحقق افتراضية عند تسجيل الدخول.',
          destructiveActionTitle: 'إزالة',
          destructiveActionSubtitle: 'إزالة تطبيق المصادقة من طرق التحقق بخطوتين',
          destructiveActionLabel: 'إزالة تطبيق المصادقة',
        },
      },
      activeDevicesSection: {
        title: 'الأجهزة النشطة',
        primaryButton: 'الأجهزة النشطة',
        detailsTitle: 'الجهاز الحالي',
        detailsSubtitle: 'هذا هو الجهاز الذي تستخدمه حاليا',
        destructiveActionTitle: 'تسجيل خروج',
        destructiveActionSubtitle: 'تسجيل الخروج من حسابك على هذا الجهاز',
        destructiveAction: 'تسجيل خروج الجهاز',
      },      
    },
    profilePage: {
        title: 'تحديث الملف الشخصي',
        imageFormTitle: 'صورة الملف الشخصي',
        imageFormSubtitle: 'تحميل الصورة',
        imageFormDestructiveActionSubtitle: 'إزالة الصورة',
        fileDropAreaTitle: 'اسحب الملف هنا، أو ...',
        fileDropAreaAction: 'اختر الملف',
        fileDropAreaHint: 'قم بتحميل صورة بصيغة JPG أو PNG أو GIF أو WEBP وأقل من 10 ميجا بايت',
        readonly: 'تم تقديم معلومات ملفك الشخصي من قبل اتصال الشركة ولا يمكن تحريرها.',
        successMessage: 'تم تحديث ملفك الشخصي.',
      },
      usernamePage: {
        title: 'تحديث اسم المستخدم',
        successMessage: 'تم تحديث اسم المستخدم الخاص بك.',
      },
      emailAddressPage: {
        title: 'إضافة عنوان البريد الإلكتروني',
        emailCode: {
          formHint: 'سيتم إرسال بريد إلكتروني يحتوي على كود التحقق إلى عنوان البريد هذا.',
          formTitle: 'كود التحقق',
          formSubtitle: 'أدخل كود التحقق المرسل إلى {{identifier}}',
          resendButton: 'لم تتلق كود؟ أعد الإرسال',
          successMessage: 'تمت إضافة البريد {{identifier}} إلى حسابك.',
        },
        emailLink: {
          formHint: 'سيتم إرسال بريد إلكتروني يحتوي على رابط التحقق إلى عنوان البريد هذا.',
          formTitle: 'رابط التحقق',
          formSubtitle: 'انقر على رابط التحقق في البريد المرسل إلى {{identifier}}',
          resendButton: 'لم تتلق رابط؟ أعد الإرسال',
          successMessage: 'تمت إضافة البريد {{identifier}} إلى حسابك.',
        },
        removeResource: {
          title: 'إزالة عنوان البريد الإلكتروني',
          messageLine1: '{{identifier}} سيتم إزالته من هذا الحساب.',
          messageLine2: 'لن تتمكن بعد الآن من تسجيل الدخول باستخدام عنوان البريد هذا.',
          successMessage: 'تمت إزالة {{emailAddress}} من حسابك.',
        },
      },
      phoneNumberPage: {
        title: 'إضافة رقم هاتف',
        successMessage: '{{identifier}} تمت إضافته إلى حسابك.',
        infoText: 'سيتم إرسال رسالة نصية تحتوي على رابط التحقق إلى هذا الرقم.',
        infoText__secondary: 'قد تنطبق أسعار الرسائل والبيانات.',
        removeResource: {
          title: 'إزالة رقم الهاتف',
          messageLine1: '{{identifier}} سيتم إزالته من هذا الحساب.',
          messageLine2: 'لن تتمكن بعد الآن من تسجيل الدخول باستخدام هذا الرقم.',
          successMessage: '{{phoneNumber}} تمت إزالته من حسابك.',
        },
      },
      connectedAccountPage: {
        title: 'إضافة حساب متصل',
        formHint: 'حدد مزودًا لربط حسابك.',
        formHint__noAccounts: 'لا توجد مزودات حساب خارجية متاحة.',
        socialButtonsBlockButton: 'ربط حساب {{provider|titleize}}',
        successMessage: 'تمت إضافة المزود إلى حسابك',
        removeResource: {
          title: 'إزالة الحساب المتصل',
          messageLine1: '{{identifier}} سيتم إزالته من هذا الحساب.',
          messageLine2:
            'لن تتمكن بعد الآن من استخدام هذا الحساب المتصل ولن تعمل الميزات التابعة له بعد الآن.',
          successMessage: '{{connectedAccount}} تمت إزالته من حسابك.',
        },
      },
      
  },  
};